### ISSUE TITLE
code

### ISSUE THREAD

**Issue by NiuYingchun** [ddsediri/StraightPCF#1]
Very nice work, when will the code be released please, thanks.

**Comment by ddsediri** [comment]
Hi @NiuYingchun, thank you for your interest in our work. I am trying to clean and prepare the code for release asap but this is a bit of a busy period with various deadlines. Hopefully in 2-3 weeks I'll be able to release it. Stay tuned! :)

**Comment by NiuYingchun** [comment]
Thanks for your reply, again I hope to get your code and would like to experiment on other datasets based on this.

**Comment by ddsediri** [comment]
Hi @NiuYingchun, I should have the repo updated with the cleaned up implementation code by the end of the coming week. I'll leave a reply on this issue when done.

**Comment by synOmO** [comment]
I also want to know when will the code be released please, thankyou～

**Comment by ddsediri** [comment]
Hi @NiuYingchun, @synOmO,

Sorry for the delay, it's been a very busy period. Code is now uploaded but I still need to clean up the instructions.

Good luck!
