### ISSUE TITLE
About Reproducing DeepPSR Accuracy

### ISSUE THREAD

**Issue by 2410183509** [ddsediri/StraightPCF#2]
Dear Author,

This is a very nice work! I am a newcomer to point cloud denoising research, and I have been studying the comparative experiments with simulated noise in other modalities (Tables 4, 5, and 6) presented in the appendix of your paper.

I noticed that the comparative methods include DeepPSR, indicating your familiarity with this approach. However, I have encountered some challenges in reproducing the accuracy of DeepPSR. I directly downloaded the data and code from their repository, set up the environment, and ran the test code. Unfortunately, the accuracy I obtained under Gaussian noise conditions was slightly lower than the reported results in the paper (CD metric: 42.74 in my reproduction versus 40.75 in the original paper). This discrepancy also appears with simulated noise in other modalities, where the accuracy is consistently lower than both the original paper and your reported results.

If possible, could you kindly provide some guidance on the details that might help in reproducing the DeepPSR accuracy more closely?

Thank you for your time and assistance.

**Comment by ddsediri** [comment]
Hi @2410183509,

The main results of DeepPSR on synthetic data is directly quoted from their original paper. We used their implementation to obtain results that were not in their paper. I think the implementation that's shared on GitHub may have some hyperparameter/implementation differences from their original code, which might affect performance. But I think the best course of action is to get in touch with the DeepPSR authors who can give you the best direction.

Best regards.
