### ISSUE TITLE
question

### ISSUE THREAD

**Issue by YBUZYX** [ddsediri/StraightPCF#5]
Hello, dear professor, your work is very good, I have encountered some problems when running the program, can you help me solve it, he has a "Segmentation fault (core dumped)" problem, I have limited ability to solve it, I hope you can help me, thank you very much.

**Comment by ddsediri** [comment]
Hi @YBUZYX,

Thank you for your interest in our work. I saw that you had previously opened and closed an issue on this so I assumed it was resolved. 

Can you attach details of your environment? Also, what script are you trying to run and what output are you getting? It would be helpful to get as much information as possible.

Also, please verify you have the following dependencies installed:
```
Python 3.9
Ubuntu 22.04
CUDA 11.8
PyTorch 2.0.1
PyTorch3D 0.7.4
PyG 2.3.1
```

Cheers,
Dasith.

**Comment by YBUZYX** [comment]
Hello Since my machine supports CUDA 11.6 up to the highest level, my PyTorch version has also changed, but I don't feel that it is a problem with Pytorch and CUDA versions, it may be a problem with other library versions, can you help me solve it Thank you very much.
![Uploading 微信图片_20240924170425.png…]()

**Comment by YBUZYX** [comment]
Hello Since my machine supports CUDA11.6 up to CUDA, my pytorch version has also changed, but I don't feel like it's a problem with pytorch and CUDA versions, it may be a problem with other library versions, in addition, the file I'm running is a test file, can you help me solve it Thank you very much
torch 1.13.1+cu116
torch-cluster 1.6.0
torch-geometric 2.6.0
pytorch3d 0.7.4

**Comment by ddsediri** [comment]
Hi, can you attach the error log? I need additional information to debug
the issue. What script were you trying to run? Where did it fail, etc.

Without that information, it's not possible to troubleshoot the problem.
Thanks!

**Comment by YBUZYX** [comment]
Dear professor, there is no error reported, only one sentence, which is Segmentation fault (core dummy)
![0ca4e8035593fb3c3d6e725a0ea991d](https://github.com/user-attachments/assets/24f2fbb9-ad7a-4dbe-815b-db8a95d03598)

**Comment by ddsediri** [comment]
Hi @YBUZYX can you try just importing torch_geometric using the command ```python -c "import torch_geometric"```. The reason is that your PyG version is mismatched and it might cause conflicts with the CUDA version (see here: https://github.com/pyg-team/pytorch_geometric/issues/4363).

Let me know how you go, thanks!

**Comment by YBUZYX** [comment]
Dear Professor, you are really impressive. As you speculated, there was an error with it. So, how should I solve it and install which version
![d15b384f8145cdb1b139929fee296a6](https://github.com/user-attachments/assets/89611b32-0c06-4e8a-98b0-ffe4c95d9df3)

**Comment by ddsediri** [comment]
Ah ok, that seems to be the mis-match issue between PyG and Pytorch+CUDA. Can you follow the instructions at the link below and install the PyG version compatible with your Pytorch and CUDA libraries: https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html#installation-from-wheels

You'll have to uninstall the current PyG package and reinstall it. Not sure if they have a wheel for Pytorch 1.13.1 but you can try something like:
`pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-1.13.1+cu116.html`

**Comment by YBUZYX** [comment]
Great, dear professor. I have solved this problem and found that there is an issue with torch_cluster, which further causes problems with torch_geometric. Thank you very much for your guidance. I wish you a happy life, good health, and a thriving career every day. I look forward to you publishing equally excellent papers.

**Comment by ddsediri** [comment]
That's great that you managed to resolve the issue, good luck with your work!
