### ISSUE TITLE
question

### ISSUE THREAD

**Issue by YBUZYX** [ddsediri/StraightPCF#7]
Dear professor, sorry to bother you again. I encountered an error while training train-vm.py. How should I solve it? It seems like I need to add the shape of the input data.
![a18997bf27344288223b23bb1de5450](https://github.com/user-attachments/assets/50f8210d-c348-4153-96b3-8919e0076ea1)

**Comment by ddsediri** [comment]
Hi, that's an issue with torchsummary version mismatch. That line prints a summary of the model. You can just comment it out and try re-running the code. If you want the model summary, just check the necessary requirements for your version of torchsummary and input them into the function, but it should just be fine to comment and run the training script.

**Comment by YBUZYX** [comment]
Hello dear professor, I don't want to comment it out because it facilitates my understanding of the model architecture, I know which version of the torch summary should be taken, do you have a solution. cheers!

**Comment by ddsediri** [comment]
Hi, sorry for the late reply. The torchsummary version for this particular environment was **torch-summary 1.4.5**.
